### Getting data from /users
GET http://localhost:3000/users

### Posting data in /users
POST http://localhost:3000/users
Content-Type: application/json

{
    "username": "samanthawill246",
    "password": "samanthawill246",
    "email": "samanthawill246@gmail.com",
    "role": "admin"
}

### Deleting id 1 from /users
DELETE http://localhost:3000/users/1

### Getting data from /services
GET http://localhost:3000/services?_page=1&_limit=3

### Posting data to /services
POST http://localhost:3000/services
Content-Type: application/json

{
    "title": "Best Tourist Packages",
    "description": "Get an inside look on all the great packages and offers we provide, hand picked by our experts and chosen by our customers, we provide you with the best package that suits your wallet as well as your loved ones.",
    "images": [
        "https://www.picnicwale.com/assets/images/international-tour-packages.jpg",
        "https://www.traveldilse.com/images/mar_images2.jpg",
        "https://www.swisstours.com/images/holiday_revamp/banner.jpg"
    ]
}

### Getting data from /packages
GET http://localhost:3000/packages/18

### Posting data to /packages
POST http://localhost:3000/packages
Content-Type: application/json

{
    "title": "Volcanoes National Park, Rwanda",
    "description": "The scenery alone — waterfalls, calderas, misty bamboo forests — makes Volcanoes National Park a worthy contender of any travel list. The mystical setting is all the more special for hosting buffaloes, birds, golden monkeys, and the elusive mountain gorilla.",
    "duration": "4 days",
    "price": "189",
    "currency": "USD",
    "services": [
        "4-5 star hotels with modern amenities",
        "Private air-conditioned vehicles for free-roaming",
        "Daily breakfast, lunch, and dinner"
    ],
    "images": [
        "https://www.youramazingplaces.com/wp-content/uploads/2019/02/volcanoes-rwanda.jpg",
        "https://www.tailormadeafrica.com/wp-content/uploads/Entrance-to-the-Volcanoes-National-Park.jpg",
        "https://gobackpacking.com/wp-content/uploads/2016/11/virunga-mountains.jpg"
    ]
}

### Patching data for id 18
PATCH http://localhost:3000/packages/18
Content-Type: application/json

{
  "title": "Zhangye National Geopark, China",
  "description": "Distinct rolling bands of orange, cream, yellow, brown, and russet against jagged mountain peaks make this geological anomaly in Gansu, China look like a psychedelic scene on Mars.",
  "duration": "3 days",
  "price": "109",
  "currency": "USD",
  "services": [
    "4-5 star hotels with modern amenities",
    "Private air-conditioned vehicles for free-roaming",
    "Daily breakfast, lunch, and dinner"
  ],
  "images": [
    "https://www.nerdstravel.com/wp-content/uploads/2020/03/Zhangye-Danxia-Landform-The-Rainbow-Mountains-of-China-scaled.jpg",
    "https://2.bp.blogspot.com/-OO7Giec5bkA/VevoKlSkbaI/AAAAAAAACWE/KoxWTLLWeQs/s1600/82012369-1c33-48c9-8746-26a802836ea8-1024x768.jpeg",
    "https://2.bp.blogspot.com/-CWoTKEteRZM/V-1SomfEITI/AAAAAAAAW9M/VkbvsAEIX7k3g8OoYkZfS-FPdq8jNxePwCLcB/s1600/%2B%25287%2529.jpg"
  ],
  "id": 18
}


### Deleting data from /packages
DELETE http://localhost:3000/packages/6

### Getting data from /feedback
GET http://localhost:3000/reviews

### Posting data to /feedback
POST http://localhost:3000/reviews
Content-Type: application/json

{
    "firstname": "Rohan",
    "lastname": "Rajput",
    "rating": "4.4",
    "description": "During our Taormina, Sicily, me and my wife intially thought that the package was a little expensive than what we thought would be reasonable, but they gave so good service for the price that I would say, that the trip was worth each dollar. Thank you so much for this amazing trip."
}